# Generated by Django 5.0.2 on 2024-08-24 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="option",
            old_name="nex_para",
            new_name="next_paragraph",
        ),
        migrations.AlterField(
            model_name="paragraph",
            name="story",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paragraphs",
                to="app.story",
            ),
        ),
    ]
