# Generated by Django 5.0.2 on 2024-08-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_nex_para_option_next_paragraph_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="option",
            old_name="next_paragraph",
            new_name="curr_paragraph",
        ),
        migrations.AddField(
            model_name="option",
            name="next_paragraphs",
            field=models.ManyToManyField(to="app.paragraph"),
        ),
    ]
